// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Api.Data;

#nullable disable

namespace Products.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Products.Api.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9211a52e-b6c6-48d1-ae00-6522c3d98b0c"),
                            ImgUri = "some",
                            Name = "a",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("92bc6a83-ca5d-4eb3-ba8b-74a3dda6db24"),
                            ImgUri = "some",
                            Name = "b",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("67514912-6ffd-4c34-a448-2892437392d6"),
                            ImgUri = "some",
                            Name = "c",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("31de73a4-5ef9-4f4e-9d77-e6cd16b7c34d"),
                            ImgUri = "some",
                            Name = "d",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("d3653a37-07c6-4f4b-905c-290ea5b320f0"),
                            ImgUri = "some",
                            Name = "e",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("9c388a2f-efff-4803-92dd-68bba8de6b38"),
                            ImgUri = "some",
                            Name = "f",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("1138b2b1-1250-4cb1-9db2-60ad82dda1f7"),
                            ImgUri = "some",
                            Name = "g",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("c4cf6d3e-e84a-4dcf-a6e3-bf41e2f51a62"),
                            ImgUri = "some",
                            Name = "h",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("374a06e4-9412-4a64-89ac-bf72d19c8a4f"),
                            ImgUri = "some",
                            Name = "i",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("9c54da3f-cad6-4e32-a72f-a8f791b4e9a6"),
                            ImgUri = "some",
                            Name = "j",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("2e3a240d-e162-4b7b-ba2f-d7aa2aa00072"),
                            ImgUri = "some",
                            Name = "k",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("a81c9f55-0419-4a56-9e60-20990979a9a4"),
                            ImgUri = "some",
                            Name = "l",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("27ef6919-b3d6-4341-9c02-177365b55818"),
                            ImgUri = "some",
                            Name = "m",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("3b8b0be8-de0c-4ad2-9868-78481993ce79"),
                            ImgUri = "some",
                            Name = "n",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("66801422-d458-4480-b487-db2293d834d0"),
                            ImgUri = "some",
                            Name = "o",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("b76f21dc-65d0-46be-b021-d168157bd107"),
                            ImgUri = "some",
                            Name = "p",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("50cc09ba-64ad-43be-9655-569400f570ff"),
                            ImgUri = "some",
                            Name = "q",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
